import { MProvider } from '@/components/providers';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning suppressHydrationWarning>
      <body suppressContentEditableWarning suppressHydrationWarning>
        <MProvider>{children}</MProvider>
      </body>
    </html>
  );
}
